name: CI

on:
    pull_request:
        branches: [main]
        types: [opened, synchronize]
        paths-ignore:
            - '*.md'
            - '.*ignore'
    push:
        branches: [main]
        paths-ignore:
            - '*.md'
            - '.*ignore'
    workflow_dispatch:

concurrency:
    group: '${{ github.workflow }}-${{ github.ref }}'
    cancel-in-progress: true

jobs:
    translate:
        runs-on: ubuntu-22.04
        permissions:
            contents: write
        if: ${{ github.event_name == 'push' }}
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  version: 8
                  cache: 'pnpm'
                  node-version: 20

            - name: Install dependencies
              run: pnpm install

            - name: Translate
              run: pnpm run start

            - name: Get last commit author
              id: last-commit
              run: echo "author=$(git log -1 --pretty=\"%an <%ae>\")" >> $GITHUB_OUTPUT

            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_author: ${{ steps.last-commit.outputs.author }}
                  commit_message: Sync translations
